CREATE DATABASE IF NOT EXISTS banco;
USE banco;

CREATE TABLE IF NOT EXISTS usuarios (
    id    INT          PRIMARY KEY AUTO_INCREMENT,
    nome  VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS empresa (
    id      INT          PRIMARY KEY AUTO_INCREMENT,
    nome    VARCHAR(100) NOT NULL,
    empresa VARCHAR(100) NOT NULL,
    cnpj    VARCHAR(18)  NOT NULL UNIQUE,
    cep     VARCHAR(9)   NOT NULL,
    email   VARCHAR(100) NOT NULL UNIQUE,
    senha   VARCHAR(255) NOT NULL
);
